# LECTURE 2 - INTRODUCTION TO PYTHON PROGRAMMING
#### prepared by: Engr. Edison A. Roxas, PECE, PhD 





## <u> A. Welcome to Jupyter (Ipython Notebooks)</u>
Take a while to adjust your bearings. Study the icons above.

There are two major types of cells:

1) Markdown cells - simple text. One can do html tags like <b>BOLD</b> or latex like $\beta$.

2) Code cells - cells where we can run code.

<b>Shortcuts</b>

1) <b>CTRL-M</b> then <b>H</b> to see help

2) <b>CTRL-M</b> then <b>S</b> to save notebook

3) <b>CTRL-ENTER</b> to Run Code but stay in the same cell

4) <b>SHIFT-ENTER</b> to Run Code and advance to the next cell

5) You can use <b>TAB</b> to see available functions. You can use <b>SHIFT-TAB</b> repeatedly for the documentation.

6) Using <b>%pylab inline</b> preceeding everything else in the notebook imports already matplotlib and numpy. It also enables our graphics to be part of the notebook.

In [ ]:
%pylab inline

## <u>B. Variables and Data Types</u>

Python uses five standard data types:
1. Numbers
2. Strings
3. Lists
4. Tuple
5. Dictionaries

### b.1. Numbers

In [1]:
varNum = 123
pi = 3.14159
VarNum_type = type(varNum)
pi_type = type(pi)

### Note:
varNum is an <b>Integer</b>, thus it does not handle numbers with decimal places while pi is a <b>Float</b> where values in the decimal place are handled.

In [2]:
print(VarNum_type)
print(pi_type)

<class 'int'>
<class 'float'>


In [3]:
pi

3.14159

### b.2. Strings

In [4]:
varText = 'This is a String'
varString = "Hello World!"

In [ ]:
print(varString)

In [ ]:
print("The length of varString is",len(varString)) #len is finding the length of the string

<b>Strings</b> may be declared with a single quote (') or double quote ("), some even use triple double quotes("""). One may use them interchangeable but some prefer to follow a specific format.

### b.3. Lists

In [5]:
varList = ["abc", 123]

In [6]:
print(varList) # prints element 0 (indexed 0 - first element)

['abc', 123]


In [7]:
print(len(varList[0]))

3


You can think of Lists as similar to ArrayLists where the <u><b>index starts at 0</b></u> and you can obtain the contents of a list by using brackets that contain the index of the element. You may also append items in the list and remove them as well.

In [9]:
print(varList[0])

abc


### b.4. Tuples

In [10]:
varTuple = ('abc', 123, "HELLO") # [] is for list & () is for vartuple

In [11]:
print(varTuple)

('abc', 123, 'HELLO')


In [12]:
print(len(varTuple)) #how many elements

3


In [13]:
print(varTuple[0])

abc


It may seem like there are no differences between Tuples and Lists other than Tuples use parenthesis while lists use brackets, but actually there are minor differences. For one thing, Tuples are fixed structures thus do not have the luxury of Lists to append or remove elements. Generally Lists have a lot of other functions readily available as opposed to using Tuples.

<b>HINT:</b> You can try to type <b><i>varList.</i></b> in one line as well as <b><i>varTuple.</i></b> and press <b>TAB</b> after the period (.) in order to view possible functions you can call from that variable. You may also try to press <b>CTRL + TAB</b> when the text cursor.

In [14]:
varList.append("HELLO") #Try also with varTuple

In [15]:
print(varList)

['abc', 123, 'HELLO']


In [16]:
print(len(varList))

3


However <b>Tuples</b> actually use less space in the memory as opposed to <b>Lists</b>, resulting in faster processing. One thing to take note of is that one would usually use Tuples when the size of the contents are static as opposed to Lists where one can use it to continuously modify the size and elements.

In [17]:
print(varList)
print(varList.__sizeof__())
print(varTuple)
print(varTuple.__sizeof__()) # finding the memory size __sizeof__
# it will show same contents but different size in byte

['abc', 123, 'HELLO']
88
('abc', 123, 'HELLO')
48


### b.5. Dictionaries

In [18]:
var = 3 
varDict = {'first':1, '2':'2nd', 3:var} # {} indicates a dictionary
varDict

{'first': 1, '2': '2nd', 3: 3}

You may also declare contents of dictionaries individually

In [19]:
varDict = {}
varDict['first'] = 1
varDict['2'] = '2nd'
varDict[3] = var
print(varDict) # print is not an output; thus no Out [33]

{'first': 1, '2': '2nd', 3: 3}


If you have experience in using JavaScript Object Notation or JSON, Python's implementation of Dictionaries are quite similar to that. You may reference an element by inserting the label of the keypair.

## <u> C. Arithmetic </u>

Python uses basic arithmetic functions which are normally present on most if not all programming languages.

### c.1. Addition

In [20]:
a = 5 + 3
a

8

### c.2. Subtraction

In [21]:
a = 5 - 3
a

2

### c.3. Multiplication

In [22]:
a = 5 * 3
a

15

### c.4. Exponent

In [23]:
a = 5 ** 3
a

125

### c.5. Division

In [26]:
a = 5 / 3 #right division
a

1.6666666666666667

### c.6. Modulus Division

In [24]:
a = 5 % 3
a

2

### c.7. Integer Division

In [25]:
a = 5 // 3
a

1

### c.8. Increment

In [32]:
a = 5
a += 1
a

6

### c.9. Decrement

In [33]:
a = 5
a -= 1
a

4

<b>NOTE:</b> Python does not support the increment/decrement syntax of <b>x++/x--</b> instead you may use the syntax of <b>x+=1/x-=1</b> which is similar to <b>x=x+1/x=x-1</b>

### c.10. String Concatenation

In [34]:
a = 'Hello ' + 'World!'
a

'Hello World!'

Strings may also be appended with the use of the plus <b>(+)</b> symbol

In [35]:
a="Hello "
b="World!"
c=a+b
c

'Hello World!'

### c.11. Complex Expressions

In [36]:
a = 3 + 5 - 6 * 2 / 4
a

5.0

## CHALLENGE!!!
### Write the following to code:

$$ g(z) = \frac{1}{1+e^{-z}}  $$

1) z = 8, and e = 2.718 should be equal to 0.9996643717

2) z = 2, and e = 2.718 should be equal to 0.8807753039

In [ ]:
z=2
g=1/(1+e**(-z))
g

<b><i>TRIVIA</i></b>: The value <b>e</b>, also called <b>Euler's number</b>, is a mathematical constant representing an irrational number that is approximately <b>2.71828</b>. Irrational, meaning the constant <b>e</b> is a real number that is unending and is unable to accurately be represented as a fraction, similar to that of <b>pi</b>.

## <u>D. Control Statements and Data Structures</u>

## d.1. Conditional Statements
In Python, curly brackets are not used to designate that multiple commands are inside a conditional statement, instead uniform spacing is used. Please take note however that the composition of the uniform spacing must be the same, such that if 4 spaces are being used, even though 4 spaces may have a visually similar result as a tab, interchanging them would produce an error statement
### a. Boolean Condition

In [37]:
x = True
if x: #default is true
    print("var x is True")
else:
    print("var x is False")

var x is True


In [38]:
x = False
if x:
    print("var x is True")
else:
    print("var x is False")

var x is False


### b. String Condition

In [39]:
x = "Hello World!"

if x == 'Hello World!':
    print("var x is Hello World!")
else:
    print("var x is not Hello World!")

var x is Hello World!


In [40]:
x = "Hello Earth!"

if x == 'Hello World!':
    print("var x is Hello World!")
else:
    print("var x is not Hello World!")

var x is not Hello World!


In [ ]:
x = '10'

if x == '10':
    print("var x is a String")
elif x == 10: #elseif
    print("var x is an Integer")
else:
    print("var x is none of the above")

In [41]:
x = 10

if x == '10':
    print("var x is a String")
elif x == 10:
    print("var x is an Integer")
else:
    print("var x is none of the above")

var x is an Integer


In [42]:
x = 5

if x == '10':
    print("var x is a String")
elif x == 10:
    print("var x is an Integer")
else:
    print("var x is none of the above")

var x is none of the above


### d. Multiple Conditions

In [43]:
x = 10

if x > 5 and x < 15 and x == 10:
    print("var x is really 10!")
else:
    print("var x is not really 10")

var x is really 10!


In [45]:
x = 15

if x > 5 and x < 15 and x == 10:
    print("var x is really 10!")
else:
    print("var x is not really 10")

var x is not really 10


In [46]:
x = 10

if x == 10 or x == 20:
    print("var x can be 10 or 20")
else:
    print("var x is not 10 nor 20")

var x can be 10 or 20


In [ ]:
x = 20

if x == 10 or x == 20:
    print("var x can be 10 or 20")
else:
    print("var x is not 10 nor 20")

In [49]:
x = 12

if x == 10 or x == 20:
    print("var x can be 10 or 20")
else:
    print('var x is not 10 nor 20')

var x is not 10 nor 20


## d.2. Loops
Similar with that of Conditional Statements, commands within a loop are designated by having a uniform spacing.
### a. For Loops

In [53]:
for var in range(0,5,2): # range(start,end,increment)
    print(var)

0
2
4


<b>NOTE:</b> The command <b>range(0,5,2)</b> is equivalent to all numbers from 0 incremented by 2 until it reaches the number less than 5

In [54]:
[v for v in range(1, 100, 5)] #produces a row vector

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

<b>NOTE:</b> range([start], [stop], [step])

### b. While Loops

In [55]:
var = 0
while var < 5:
    print(var)
    var += 2

0
2
4


### c. Nested Loops - condition within a condition


In [65]:
x = 0
while x < 5:
    for y in range(0, x): # : default is TRUE & range without step is defalut as 1
        print(y ,end='')
    x+=1
    print()



0
01
012
0123


Always take note that there should be a colon <b>(:)</b> on the line where one declares the loop or condition

## Lists

In [67]:
pi = 3.14159
varList = [1, 2, 'A', 'B', 'Hello!', pi]

In [68]:
print(varList[0])

1


For more information regarding lists, this has been discussed on section B. Data Types and Variables.
You can chose to insert different datatypes in a single list.

In [69]:
print(varList[4])

Hello!


You may call the content of the list through indexing

In [72]:
varList.append('World!')

In [73]:
print(varList)
print(varList[6])

[1, 2, 'A', 'B', 'Hello!', 3.14159, 'World!', 'World!']
World!


You may also append items in the list. The example above shows you that when you added a new list item, it would be added towards the end of list

In [74]:
len(varList)

8

You may obtain the number of elements in a list by calling the <b>len()</b> function

In [75]:
print(varList[5])

3.14159


In [76]:
varList.remove(pi)

In [77]:
print(varList[5])

World!


Initially <b>varList[5]</b> was called and the result was 3.14159, however when the <b>remove()</b> function was called, it iterates though the list looking for the first match then erases that value.

## Dictionaries

In [78]:
var = "Hello World!"
varDict = {'first' : 123, 2 : 'abc', '3' : var, 4:['lista', 'listb']}

In [79]:
print(varDict)

{'first': 123, 2: 'abc', '3': 'Hello World!', 4: ['lista', 'listb']}


In [80]:
print(varDict['first'])

123


In [81]:
print(varDict[2])

abc


In [83]:
print(varDict['3'])
print(vardict[3])

Hello World!


KeyError: 3

In [84]:
print(varDict[4])

['lista', 'listb']


In [85]:
print(varDict[4][1])

listb


In [86]:
len(varDict)

4

## Slicing

<b>NOTE</b> <i> list([start]: [end])
start is inclusive and end is exclusive

In [87]:
varList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
varList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [88]:
varList[:5] # : means from the start index

[1, 2, 3, 4, 5]

In [89]:
varList[5:] # : means end inclusive

[6, 7, 8, 9, 10]

In [90]:
varList[:-2] 

[1, 2, 3, 4, 5, 6, 7, 8]

In [96]:
varList[-2:] 

[9, 10]

In [97]:
print(varList[2:-2])

[3, 4, 5, 6, 7, 8]


In [99]:
varList[2:8:2]

[3, 5, 7]

<b>NOTE</b> <i>list([start]: end : [
step])

# Vectors, Matrices and Computation
In Python, you can use <b>NUMPY</b> or <b>np</b> through the use of <b>import numpy as np</b> in order to easily use functions for vectors and matrices.

In [100]:
import numpy as np #everytime np (or any other name) is called NP is imported

In [101]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

It's the same as just: 

In [102]:
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
print(np.arange(0, 100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## Computing vector computations
### Vector to scalar

In [104]:
varArray = np.arange(0, 5)
varArray

array([0, 1, 2, 3, 4])

In [105]:
varArray * 2

array([0, 2, 4, 6, 8])

### Vector to vector: Dot Product

In [106]:
varArrayA = np.arange(0,5)
varArrayB = np.arange(5,10)

In [107]:
print(varArrayA)

[0 1 2 3 4]


In [108]:
print(varArrayB)

[5 6 7 8 9]


In [109]:
print(np.dot(varArrayA, varArrayB))

80


### Vector to vector: Element-wise multiplication

In [110]:
varArrayA * varArrayB

array([ 0,  6, 14, 24, 36])

## Matrix to Scalar: Element-wise multiplication

In [117]:
mat_a = np.random.randint(0, 5, size=(4,4))

In [118]:
print(mat_a)

[[3 3 2 2]
 [4 3 3 3]
 [4 1 4 3]
 [2 4 3 3]]


In [ ]:
print(mat_a * 2)

## Matrix to Matrix: Matrix Multiplication 

In [ ]:
mat_a * mat_a

## Advanced Matrix Operations

In [ ]:
from scipy.linalg import eig #linear algebra from scipy library

In [ ]:
eig(mat_a)

# Enter Pandas

In [ ]:
import pandas as pd 

In [ ]:
data = pd.read_csv("movie_metadata.csv") #uses variable data so as not to edit the original file
data

In [ ]:
data.shape #For the Number of Rows and Columns & row 1 is the name of the label

In [ ]:
data.columns #For the Name of Columns

In [ ]:
data.describe() #For the Statistical Summary

In [ ]:
data.corr() #For the Data Correlations CAN BE USED IN GAIT ANALYSIS...

In [ ]:
data.isnull().sum().sort_values(ascending=False) #To See Columns for Missing Value and its sum

In [ ]:
cleaned_data_filled = data.fillna(0) # All null values will be replaced by the value 0

In [ ]:
cleaned_data_filled.isnull().sum().sort_values(ascending=False) #To See Columns for Missing Value

In [ ]:
cleaned_data_removed = data.dropna(axis=0, how='any') #axis=0 is ROW & axis=1 is COLUMN

In [ ]:
cleaned_data_removed.isnull().sum().sort_values(ascending=False) #To See Columns for Missing Value

In [ ]:
cleaned_data_removed.shape #For the Number of Rows and Columns of the Processed Data

In [ ]:
cleaned_data_removed.to_csv('cleaned_movie_metada.csv') #To have a CSV copy of Cleaned Data

## Slicing Data Frames

In [ ]:
data[:4] #extracts rows 0,1,2,3

## Indexing Columns

In [ ]:
data.director_name[:4]

In [ ]:
data.actor_2_name[:10]

In [ ]:
cols = ["movie_title","director_name"]
data[cols][:5]

In [ ]:
cols = ["movie_title","gross"] #create a column containing movie title and gross
data[cols][:10]

## Indexing Rows

In [ ]:
data.iloc[10:12] #locate specific location of rows [10:12]

## Find Movies by James Cameron

In [ ]:
data[data.director_name == 'James Cameron']

## Sort Films by Gross Earnings

In [ ]:
sorted_data = data.sort_values(by="gross", ascending=False)
sorted_data[:5]

## Multiple Conditions: Find films from the Canada that have Hugh Jackman as the actor_1_name

In [ ]:
data[(data['country'] == 'Canada') & (data['actor_1_name'] == 'Hugh Jackman')]

## Challenge! Get the Top 5 films of Michael Bay

In [ ]:
MB_data = data[data.director_name == 'Michael Bay']
MB_data = MB_data.sort_values(by="gross", ascending=False)
MB_data[:5]

###### Engr. Edison A. Roxas, PECE, PhD
earoxas@ust.edu.ph